[package]
name = "flair_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustserve = { path = "../../rustserve" }

http = "0.2"
anyhow = "1.0"

futures = "0.3.1" 
